### ISSUE TITLE
View's events attribute being optimized out (Breaks delegateEvents)

### ISSUE THREAD

**Issue by Alphadelta14** [lukeasrodgers/backbone-js-externs#4]
While usually optional, `View.events` should not be optimized because `View.prototype.delegateEvents()` check for `this.events` to exist if there are no arguments provided.

**Comment by lukeasrodgers** [comment]
Thanks @Alphadelta14, I'll add support for all of the view options specified here: https://github.com/jashkenas/backbone/blob/bc59f5338c563d5ad808d29e71a5acf1ded96bab/backbone.js#L1046
